articles/urls.py
from django.conf.urls import url
from . import views

app_name = 'articles'

urlpatterns = [
    url(r'^$', views.article_list, name="list"),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"),
]

eval_python/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home),
    url(r'^contact/', views.contact),
    
    url(r'^articles/', include('articles.urls')),

    url(r'^projets/', include('projets.urls')),
]

urlpatterns += staticfiles_urlpatterns()

projets/urls.py
from django.conf.urls import url
from . import views

app_name = 'projets'

urlpatterns = [
    url(r'^$', views.projet_list, name='list'),
    url(r'^create/$', views.projet_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', views.projet_detail, name="detail"),
    
    url(r'^edit/(?P<slug>[\w-]+)/$', views.projet_edit, name="edit"),
    url(r'^edit/$', views.projet_edit, name="edit"),

    url(r'^delete/(?P<slug>[\w-]+)/$', views.projet_delete, name="delete"),
]

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(blank=False)
    description = models.TextField()
    image_url = models.CharField(max_length=255)
    date = models.DateField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.description[:50] + '...'

# python3 manage.py makemigrations
# python3 manage.py migrate

projets/models.py
from django.db import models

# Create your models here.
class Projet(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(blank=False)
    description = models.TextField()
    image_url = models.CharField(max_length=255)
    technology = models.CharField(max_length=255)
    repo_url = models.CharField(max_length=255, blank=False)
    website_url = models.CharField(max_length=255, blank=False)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

    def snippet(self):
        return self.description[:50] + '...'

# python3 manage.py makemigrations
# python3 manage.py migrate

projets/forms.py
from django import forms
from . import models

class CreateProjet(forms.ModelForm):
    class Meta:
        model = models.Projet
        fields = ['name', 'slug', 'description', 'image_url', 'technology', 'repo_url', 'website_url']

articles/views.py
from django.shortcuts import render
from .models import Article
from django.http import HttpResponse

# Create your views here.
def article_list(request):
    articles = Article.objects.all()
    return render(request, 'articles/article_list.html', {'articles':articles})

def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article':article})

eval_python/views.py
from django.http import HttpResponse
from django.shortcuts import render 
from django.db import models
from projets.models import Projet

def home(request):
    projets = Projet.objects.all()
    return render(request, 'home.html', {'projets':projets})

def contact(request):
    return render(request, 'contact.html')

projets/views.py
from django.shortcuts import render, redirect
from .models import Projet
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from . import forms
from django.shortcuts import get_object_or_404 

# Create your views here.
def projet_list(request):
    projets = Projet.objects.all()
    return render(request, 'projets/projet_list.html', {'projets':projets})

def projet_detail(request, slug):
    projet = Projet.objects.get(slug=slug)
    return render(request, 'projets/projet_detail.html', {'projet':projet})

@login_required
def projet_create(request):
    if request.method =='POST':
        form = forms.CreateProjet(request.POST)
        if form.is_valid():
            form.save()
            return redirect('projets:list')
    else:
        form = forms.CreateProjet()
    return render(request, 'projets/projet_create.html', {'form':form})

@login_required
def projet_edit(request, slug):
    context = {} 
    obj = get_object_or_404(Projet, slug = slug) 
    form = forms.CreateProjet(request.POST or None, instance = obj) 
    if form.is_valid(): 
        form.save() 
        return redirect('/projets/') 
    context["form"] = form 
    return render(request, 'projets/projet_edit.html', context)

@login_required
def projet_delete(request, slug):
    projet = Projet.objects.get(slug=slug)
    projet.delete()
    return redirect('/projets/')

articles/templates/articles/article_detail.html
{% extends 'base_layout.html'%} {% block content %}
<h1><a href="{% url 'articles:list' %}">Liste des articles</a></h1>

<div class="article-detail">
    <div class="article">
        <h2>{{article.title}}</h2>
        <img src="{{article.image_url}}" alt="">
        <p>{{article.description}}</p>
        <p>{{article.date}}</p>
        <p>{{article.author}}</p>
    </div>
</div>
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html'%} {% block content %}
<!--<h1><a href="{% url 'articles:list' %}">Liste des articles</a></h1>-->

<div class="articles">
    {% for article in articles %}
    <div class="article">
        <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
        <img src="{{article.image_url}}" alt="">
        <p>{{article.snippet}}</p>
        <p>{{article.date}}</p>
        <hr>
    </div>
    {% endfor %}
</div>
{% endblock %}

projets/templates/projets/projet_create.html
{% extends 'base_layout.html'%} {% block content %}
<div class="create-projet">
    <h2>Créer un projet</h2>
    <form action="{% url 'projets:create' %}" method="post">
        {% csrf_token %} {{form}}
        <input type="submit" value="Créer">
    </form>
</div>
<script src="/static/slugify.js"></script>
{% endblock %}

projets/templates/projets/projet_detail.html
{% extends 'base_layout.html'%} {% block content %}
<h1><a href="{% url 'projets:list' %}">Liste des projets</a></h1>

<div class="article-detail">
    <div class="article">
        <h2>{{projet.name}}</h2>
        <img src="{{projet.image_url}}" alt="">
        <p>{{projet.description}}</p>
        <p>{{projet.technology}}</p>
        <p>{{projet.repo_url}}</p>
        <p>{{projet.website_url}}</p>
        <p>{{projet.date}}</p>
        {% if user.is_authenticated %}
        <h3><a href="{% url 'projets:edit' slug=projet.slug %}">Editer</a></h3>
        <h3><a href="{% url 'projets:delete' slug=projet.slug %}">Supprimer</a></h3>
        {% endif %}
    </div>
</div>
{% endblock %}

projets/templates/projets/projet_edit.html
{% extends 'base_layout.html'%} {% block content %}
<div class="edit-projet">
    <h2>Editer un projet</h2>
    <form action="" method="post">
        {% csrf_token %} {{ form.as_p }}
        <input type="submit" value="Editer">
    </form>
</div>
<script src="/static/slugify.js "></script>

{% endblock %}

projets/templates/projets/projet_list.html
{% extends 'base_layout.html'%} {% block content %}
<!-- <h1><a href="{% url 'projets:list' %}">Liste des projets</a></h1> -->
{% if user.is_authenticated %}
<h2><a href="{% url 'projets:create' %}">Ajouter un projet</a></h2>
{% endif %}

<div class="projets">
    {% for projet in projets %}
    <div class="article">
        <h2><a href="{% url 'projets:detail' slug=projet.slug %}">{{projet.name}}</a></h2>
        <img src="{{projet.image_url}}" alt="">
        <p>{{projet.snippet}}</p>
        <p>{{projet.date}}</p>
        <hr>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <title>My Wonderful Project</title>
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <link rel="stylesheet" href="{% static '/bootstrap-grid/bootstrap-grid.min.css' %}" />

</head>

<body>

    <header id="header">
        <h1><a href="/">Abdellah Skoundri</a></h1>
        <nav class="links">
            <ul>
                <li><a href="/projets">Projets</a></li>
                <li><a href="/articles">Articles</a></li>
                <li><a href="/contact">Contact</a></li>
            </ul>
        </nav>
        {% if user.is_authenticated %}
        <nav class="links">
            <ul>
                <li class="">
                    <a class="" href="/admin">Administration</a>
                </li>
            </ul>
        </nav>
        {% endif %}
    </header>

    <div id="wrapper">
        <div class="container">
            <div class="row">
                <section>
                    <h3>Me contacter</h3>
                    <form method="post" action="#">
                        <div class="row gtr-uniform">
                            <div class="col-6 col-12-xsmall">
                                <input type="text" name="" id="demo-name" value="" placeholder="Name" />
                            </div>
                            <div class="col-6 col-12-xsmall">
                                <input type="text" name="" id="demo-name" value="" placeholder="Prenom" />
                            </div>
                            <div class="col-12">
                                <input type="email" name="demo-email" id="demo-email" value="" placeholder="Email" />
                            </div>
                            <div class="col-12">
                                <textarea name="demo-message" id="demo-message" placeholder="Enter your message" rows="6"></textarea>
                            </div>
                            <div class="col-12">
                                <ul class="actions">
                                    <li><input type="submit" value="Send Message" /></li>
                                </ul>
                            </div>
                        </div>
                    </form>
                </section>
            </div>
            <div class="row align-items-center">
                <div class="col-6">
                    <section id="footer">
                        <ul class="icons">
                            <li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
                            <li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
                            <li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
                            <li><a href="#" class="icon solid fa-rss"><span class="label">RSS</span></a></li>
                            <li><a href="#" class="icon solid fa-envelope"><span class="label">Email</span></a></li>
                        </ul>
                        <p class="copyright">&copy; Untitled. Design: <a href="http://html5up.net">HTML5 UP</a>. Images: <a href="http://unsplash.com">Unsplash</a>.</p>
                    </section>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <title>AbSk.</title>
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <link rel="stylesheet" href="{% static '/bootstrap-grid/bootstrap-grid.min.css' %}">

</head>

<body>

    <div id="wrapper">

        <header id="header">
            <h1><a href="/">AbSk.</a></h1>
            <nav class="links">
                <ul>
                    <li><a href="/projets">Projets</a></li>
                    <li><a href="/articles">Articles</a></li>
                    <li><a href="/contact">Contact</a></li>
                </ul>
            </nav>
            {% if user.is_authenticated %}
            <nav class="links">
                <ul>
                    <li class="">
                        <a class="" href="/admin">Administration</a>
                    </li>
                </ul>
            </nav>
            {% endif %}
        </header>

        <!-- 
            <div class="block">
            {% block content %} {% endblock %}
            </div> 
        -->
        <div class="row">

            <div class="col-sm-3">
                <section id="sidebar">

                    <!-- Intro -->
                    <section id="intro">
                        <img src="{% static '/images/logo3.png' %}" alt="" />
                    </section>

                    <!-- About -->
                    <section class="blurb">
                        <h2>About</h2>
                        <p>Efficace, plein d’entrain et toujours de bonne humeur. Je m’applique à ce que mon espace de travail et mes relations avec mes collaborateurs soient agréables et vitaminés tout en restant professionnels.</p>
                        <ul class="actions">
                            <li><a href="#" class="button">Learn More</a></li>
                        </ul>
                    </section>

                    <!-- Mini Posts 
                    <section>
                        <div class="mini-posts">

                            
                            <article class="mini-post">
                                <header>
                                    <h3><a href="single.html">Vitae sed condimentum</a></h3>
                                    <time class="published" datetime="2015-10-20">October 20, 2015</time>
                                    <a href="#" class="author"><img src="{% static '/images/avatar.jpg' %}" alt="" /></a>
                                </header>
                                <a href="single.html" class="image"><img src="{% static '/images/pic04.jpg' %}" alt="" /></a>
                            </article>

                            
                            <article class="mini-post">
                                <header>
                                    <h3><a href="single.html">Rutrum neque accumsan</a></h3>
                                    <time class="published" datetime="2015-10-19">October 19, 2015</time>
                                    <a href="#" class="author"><img src="{% static '/images/avatar.jpg' %}" alt="" /></a>
                                </header>
                                <a href="single.html" class="image"><img src="{% static '/images/pic05.jpg' %}" alt="" /></a>
                            </article>

                            
                            <article class="mini-post">
                                <header>
                                    <h3><a href="single.html">Odio congue mattis</a></h3>
                                    <time class="published" datetime="2015-10-18">October 18, 2015</time>
                                    <a href="#" class="author"><img src="{% static '/images/avatar.jpg' %}" alt="" /></a>
                                </header>
                                <a href="single.html" class="image"><img src="{% static '/images/pic06.jpg' %}" alt="" /></a>
                            </article>

                            
                            <article class="mini-post">
                                <header>
                                    <h3><a href="single.html">Enim nisl veroeros</a></h3>
                                    <time class="published" datetime="2015-10-17">October 17, 2015</time>
                                    <a href="#" class="author"><img src="{% static '/images/avatar.jpg' %}" alt="" /></a>
                                </header>
                                <a href="single.html" class="image"><img src="{% static '/images/pic07.jpg' %}" alt="" /></a>
                            </article>

                        </div>
                    </section> -->

                    <!-- Posts List -->
                    <section>
                        <ul class="posts">
                            <li>
                                <article>
                                    <header>
                                        <h3><a href="single.html">Lorem ipsum fermentum ut nisl vitae</a></h3>
                                        <time class="published" datetime="2015-10-20">October 20, 2015</time>
                                    </header>
                                    <a href="single.html" class="image"><img src="{% static '/images/pic08.jpg' %}" alt="" /></a>
                                </article>
                            </li>
                            <li>
                                <article>
                                    <header>
                                        <h3><a href="single.html">Convallis maximus nisl mattis nunc id lorem</a></h3>
                                        <time class="published" datetime="2015-10-15">October 15, 2015</time>
                                    </header>
                                    <a href="single.html" class="image"><img src="{% static '/images/pic09.jpg' %}" alt="" /></a>
                                </article>
                            </li>
                            <li>
                                <article>
                                    <header>
                                        <h3><a href="single.html">Euismod amet placerat vivamus porttitor</a></h3>
                                        <time class="published" datetime="2015-10-10">October 10, 2015</time>
                                    </header>
                                    <a href="single.html" class="image"><img src="{% static '/images/pic10.jpg' %}" alt="" /></a>
                                </article>
                            </li>
                            <li>
                                <article>
                                    <header>
                                        <h3><a href="single.html">Magna enim accumsan tortor cursus ultricies</a></h3>
                                        <time class="published" datetime="2015-10-08">October 8, 2015</time>
                                    </header>
                                    <a href="single.html" class="image"><img src="{% static '/images/pic11.jpg' %}" alt="" /></a>
                                </article>
                            </li>
                            <li>
                                <article>
                                    <header>
                                        <h3><a href="single.html">Congue ullam corper lorem ipsum dolor</a></h3>
                                        <time class="published" datetime="2015-10-06">October 7, 2015</time>
                                    </header>
                                    <a href="single.html" class="image"><img src="{% static '/images/pic12.jpg' %}" alt="" /></a>
                                </article>
                            </li>
                        </ul>
                    </section>


                    <!-- Footer -->
                    <section id="footer">
                        <ul class="icons">
                            <li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
                            <li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
                            <li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
                            <li><a href="#" class="icon solid fa-rss"><span class="label">RSS</span></a></li>
                            <li><a href="#" class="icon solid fa-envelope"><span class="label">Email</span></a></li>
                        </ul>
                        <p class="copyright">&copy; Untitled. Design: <a href="http://html5up.net">HTML5 UP</a>. Images: <a href="http://unsplash.com">Unsplash</a>.</p>
                    </section>

                </section>

            </div>

            <div class="col-sm-9">
                <!-- Post -->
                {% for projet in projets %}
                <article class="post">
                    <header>
                        <div class="title">
                            <h2><a href="single.html">{{projet.name}}</a></h2>
                            <p>{{projet.snippet}}</p>
                        </div>
                        <div class="meta">
                            <time class="published" datetime="2015-11-01">{{projet.date}}</time>
                            <a href="#" class="author"><span class="name">admin</span><img src="{% static '/images/avatar.jpg' %}" alt="" /></a>
                        </div>
                    </header>
                    <a href="single.html" class="image featured"><img src="{% static '/images/pic01.jpg' %}" alt="" /></a>
                    <p>Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl. Sed mattis nunc id lorem euismod placerat. Vivamus porttitor magna enim, ac accumsan tortor cursus at. Phasellus sed ultricies mi non congue ullam corper. Praesent
                        tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.</p>
                    <footer>
                        <ul class="actions">
                            <li><a href="single.html" class="button large">Continue Reading</a></li>
                        </ul>
                        <ul class="stats">
                            <li><a href="#">General</a></li>
                            <li><a href="#" class="icon solid fa-heart">28</a></li>
                            <li><a href="#" class="icon solid fa-comment">128</a></li>
                        </ul>
                    </footer>
                </article>
                {% endfor %}
            </div>
        </div>

    </div>

    <div class="article">
        <h2></h2>
        <img src="{{projet.image_url}}" alt="">
        <p>{{projet.snippet}}</p>
        <p></p>
        <hr>
    </div>
    </div>
</body>

</html>